#!/usr/bin/env python3
"""Scan a project folder and rank its files by how far they are from Jed's writing style.

This is step one of the plan-first restyle. It only reads. It never changes a file.

Usage:
    python3 plan_scan.py                       scan the current folder
    python3 plan_scan.py docs/ README.md       scan only these paths
    python3 plan_scan.py --code                also read comments and docstrings in source files
    python3 plan_scan.py --json                full result as JSON, for writing the plan
    python3 plan_scan.py --exclude "drafts/*" --exclude legacy   skip paths (also read from .signatureignore)
    python3 plan_scan.py --all                 don't skip files that look like samples or third-party text
    python3 plan_scan.py --top 40              rows shown in the table (default 25)
    python3 plan_scan.py --max-findings 12     findings kept per file (default 20)

It uses `git ls-files` inside a git repo, so .gitignore is respected. Elsewhere it walks the folder
and skips the usual noise (node_modules, virtualenvs, build output, hidden folders).

Exit codes: 0 done, 2 nothing to scan or a bad path.
"""
import argparse
import fnmatch
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import ai_check  # noqa: E402

__version__ = "1.0.0"

# Prose Jed writes. These are scanned by default.
PROSE_EXT = {".md", ".markdown", ".txt", ".rst", ".docx", ".pptx"}
# Files that exist for agents or tools, not readers. Never scanned.
# STYLE_PLAN.md quotes the text it plans to change, so scanning it would always rank it worst.
SKIP_NAMES = {"claude.md", "agents.md", "gemini.md", "memory.md", "style_plan.md", "license", "licence", "notice",
              "codeowners", "package-lock.json", "yarn.lock", "poetry.lock", "uv.lock"}
SKIP_DIRS = {".git", "node_modules", "venv", ".venv", "env", "__pycache__", "dist", "build", ".next",
             "target", "vendor", ".tox", ".mypy_cache", ".pytest_cache", "site-packages", ".idea", ".vscode"}
# A source file bigger than this is almost certainly generated or data. 300 KB is about 50,000 words.
MAX_BYTES = 300_000
# Decks and Word files are zip files that hold images, so they get a far higher cap. Only their text is read.
MAX_BYTES_ZIP = 25_000_000
# A file this long, in words, is almost always a log or a data dump, not something written for readers.
MAX_WORDS = 20_000
# Paths that usually hold text Jed did not write: sample data, test fixtures, course material and
# transcripts. They are skipped unless --all is given, and the plan asks Jed to confirm either way.
NOT_JEDS = re.compile(r"(^|[/_\-.])(sample|samples|fixture|fixtures|testdata|test_data|mock|mocks|dummy|lorem|"
                      r"syllabus|transcript|transcripts|handout|handouts|reading|readings|third_party|vendor|"
                      r"corpus|dataset|datasets|archive|archived|backup|backups|deprecated)([/_\-.]|$)", re.I)
IGNORE_FILE = ".signatureignore"
# Files like this say they were generated, so a person should not edit them by hand.
GENERATED = re.compile(r"(do not edit|auto-?generated|generated by|@generated)", re.I)

REGISTER_HINTS = [  # first match wins, checked against the lowercase relative path
    (re.compile(r"(script|voiceover|speaker|narration)"), "script"),
    (re.compile(r"(slide|deck|presentation)"), "slides"),
    (re.compile(r"(linkedin|medium|blog|post)"), "post"),
    (re.compile(r"(customer|client|faq|q-?and-?a|qa)"), "customer"),
    (re.compile(r"(discussion|assignment|essay|paper|cs\d{4})"), "course"),
]


def infer_register(rel, suffix):
    if suffix == ".pptx":
        return "slides"
    low = rel.lower()
    for pattern, register in REGISTER_HINTS:
        if pattern.search(low):
            return register
    return "doc"


def git_files(root):
    """Tracked and untracked-but-not-ignored files, or None if root is not a git repo."""
    try:
        out = subprocess.run(["git", "-C", str(root), "ls-files", "--cached", "--others", "--exclude-standard", "-z"],
                             capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if out.returncode != 0:
        return None
    return [Path(p) for p in out.stdout.split("\0") if p]


def walk_files(root):
    found = []
    for base, dirs, names in os.walk(root):
        dirs[:] = sorted(d for d in dirs if d not in SKIP_DIRS and not d.startswith("."))
        for name in sorted(names):
            found.append((Path(base) / name).relative_to(root))
    return found


def candidates(root, paths):
    files = git_files(root)
    if files is None:
        files = walk_files(root)
    if paths:
        wanted = [Path(p) for p in paths]
        files = [f for f in files if any(f == w or w in f.parents for w in wanted)]
    return files


def load_ignore(root, extra):
    patterns = list(extra or [])
    try:
        for line in (root / IGNORE_FILE).read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                patterns.append(line)
    except OSError:
        pass
    return patterns


def is_ignored(rel, patterns):
    text = rel.as_posix()
    for pat in patterns:
        pat = pat.rstrip("/")
        if fnmatch.fnmatch(text, pat) or fnmatch.fnmatch(text, pat + "/*") or any(fnmatch.fnmatch(part, pat) for part in rel.parts):
            return True
    return False


def classify(root, rel, include_code, patterns=(), keep_all=False):
    """Return (scan?, reason) for one relative path."""
    if is_ignored(rel, patterns):
        return False, "excluded"
    if not keep_all and NOT_JEDS.search(rel.as_posix()):
        return False, "probably not Jed's writing (sample, transcript, syllabus or similar). Use --all to include"
    parts = {p.lower() for p in rel.parts}
    if parts & SKIP_DIRS or any(p.startswith(".") and p not in (".", "..") for p in rel.parts[:-1]):
        return False, "skipped folder"
    if rel.name.lower() in SKIP_NAMES or rel.stem.lower() in SKIP_NAMES:
        return False, "agent or tool file"
    suffix = rel.suffix.lower()
    is_code = suffix in ai_check.CODE_EXT
    if suffix not in PROSE_EXT and not (include_code and is_code):
        return False, "code (use --code)" if is_code else "not prose"
    try:
        size = (root / rel).stat().st_size
    except OSError:
        return False, "unreadable"
    if size > (MAX_BYTES_ZIP if suffix in (".docx", ".pptx") else MAX_BYTES):
        return False, "too large, probably generated or data"
    if size == 0:
        return False, "empty"
    return True, ""


def scan(root, paths=None, include_code=False, max_findings=20, exclude=None, keep_all=False):
    root = Path(root).resolve()
    patterns = load_ignore(root, exclude)
    scanned, skipped = [], []
    for rel in candidates(root, paths):
        ok, reason = classify(root, rel, include_code, patterns, keep_all)
        if not ok:
            if reason not in ("not prose", "skipped folder"):  # those would be a very long, useless list
                skipped.append({"path": str(rel), "reason": reason})
            continue
        suffix = rel.suffix.lower()
        try:
            raw = ai_check.read_text(str(root / rel))
        except Exception as e:  # a bad docx should not stop the scan
            skipped.append({"path": str(rel), "reason": "could not read: %s" % e})
            continue
        if suffix in (".md", ".markdown", ".txt", ".rst") and GENERATED.search(raw[:400]):
            skipped.append({"path": str(rel), "reason": "looks generated"})
            continue
        register = "code" if suffix in ai_check.CODE_EXT else infer_register(str(rel), suffix)
        if len(raw.split()) > MAX_WORDS:
            skipped.append({"path": str(rel), "reason": "over %d words, probably a log or data dump" % MAX_WORDS})
            continue
        result = ai_check.analyse(raw, register, suffix)
        counts = {"P0": 0, "P1": 0, "P2": 0}
        for f in result["findings"]:
            counts[f["tier"]] += 1
        scanned.append({
            "path": str(rel), "register": register, "words": result["words"], "score": result["score"],
            "verdict": result["verdict"], "counts": counts, "rhythm": result["rhythm"],
            "findings": [{k: f[k] for k in ("tier", "label", "line", "snippet", "advice")}
                         for f in result["findings"] if f["tier"] != "P2"][:max_findings],
        })
    # Worst first: any P0 matters most, then P1, then the overall score.
    scanned.sort(key=lambda f: (-f["counts"]["P0"], -f["counts"]["P1"], -f["score"], f["path"]))
    return {"root": str(root), "scanned": scanned, "skipped": skipped, "include_code": include_code,
            "folders": folder_summary(scanned), "ignore_patterns": patterns}


def folder_summary(scanned):
    """Files and findings per top-level folder, so the plan can ask Jed to confirm the scope."""
    folders = {}
    for f in scanned:
        top = f["path"].split("/")[0] if "/" in f["path"] else "(top level)"
        row = folders.setdefault(top, {"files": 0, "P0": 0, "P1": 0})
        row["files"] += 1
        row["P0"] += f["counts"]["P0"]
        row["P1"] += f["counts"]["P1"]
    return dict(sorted(folders.items(), key=lambda kv: (-kv[1]["P0"], kv[0])))


def markdown(result, top=25):
    rows = result["scanned"]
    out = ["Scanned %d files in %s" % (len(rows), result["root"]), ""]
    if not rows:
        return "\n".join(out + ["Nothing to scan."])
    out += ["By folder:", "", "| Folder | Files | P0 | P1 |", "|---|---|---|---|"]
    out += ["| %s | %d | %d | %d |" % (name, v["files"], v["P0"], v["P1"]) for name, v in list(result["folders"].items())[:15]]
    out += ["", "Worst files first:", ""]
    out.append("| File | Register | Words | Score | P0 | P1 | P2 | Verdict |")
    out.append("|---|---|---|---|---|---|---|---|")
    for f in rows[:top]:
        c = f["counts"]
        out.append("| %s | %s | %d | %.1f | %d | %d | %d | %s |" % (
            f["path"], f["register"], f["words"], f["score"], c["P0"], c["P1"], c["P2"], f["verdict"]))
    if len(rows) > top:
        out.append("| and %d more files | | | | | | | |" % (len(rows) - top))
    clean = sum(1 for f in rows if f["verdict"] == "clean")
    out += ["", "%d of %d files are already clean." % (clean, len(rows))]
    if result["skipped"]:
        out += ["", "Skipped:"]
        out += ["- %s (%s)" % (s["path"], s["reason"]) for s in result["skipped"][:15]]
        if len(result["skipped"]) > 15:
            out.append("- and %d more" % (len(result["skipped"]) - 15))
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="*", help="files or folders to scan, relative to the current folder (default: everything)")
    ap.add_argument("--code", action="store_true", help="also read comments and docstrings in source files")
    ap.add_argument("--json", action="store_true", help="print the full result as JSON")
    ap.add_argument("--exclude", action="append", metavar="GLOB", help="skip paths matching this pattern. Repeatable")
    ap.add_argument("--all", action="store_true", help="include files that look like samples or third-party text")
    ap.add_argument("--top", type=int, default=25, metavar="N", help="rows shown in the table (default 25)")
    ap.add_argument("--max-findings", type=int, default=20, metavar="N", help="findings kept per file (default 20)")
    ap.add_argument("--version", action="version", version="plan_scan " + __version__)
    args = ap.parse_args(argv)

    root = Path.cwd()
    for p in args.paths:
        if not (root / p).exists():
            print("plan_scan: no such path: %s" % p, file=sys.stderr)
            return 2
    result = scan(root, args.paths, args.code, args.max_findings, args.exclude, args.all)
    if not result["scanned"]:
        print("plan_scan: nothing to scan here. Prose files are .md, .txt, .rst, .docx and .pptx. Add --code for comments.", file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2) if args.json else markdown(result, args.top))
    return 0


if __name__ == "__main__":
    sys.exit(main())
